Homework 2
Ivan-Nebogatikov/Homeworks pull request #28
Opened 2016-09-29 13:28 UTC by Ivan-Nebogatikov

Added solution for Homework 2

2016-11-29 08:15 UTC, yurii-litvinov requested changes

2016-11-29 08:15 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2/Computer.cs
> +        public Computer(OS os, bool infection, List<int> neigh)
neigh --- странное имя параметра, такое чувство, что его писали-писали, надоело, бросили

2016-11-29 08:15 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2/Network.cs
> +                    if (new Random().NextDouble() < computers[neighbour].GetOSProbability())
Все рандомы, созданные в одну миллисекунду, будут возвращать одинаковое значение (они инициализируются по умолчанию таймером), так что так нельзя. Надо один рандом на приложение по-хорошему.

2016-11-29 08:15 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2/Network.cs
> +                        computers[neighbour].Infected = true;
Мм, так они могут позаражаться, даже если в сети изначально вообще не было вирусов, нет?

2016-11-29 08:15 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2Tests/NetworkTests.cs
> +            network.StartNetwork();
Тестировать надо как-то по-другому, потому что сейчас сеть, которая просто сразу все компьютеры помечает как заражённые, такому тесту удовлетворяет.

2016-11-29 12:58 UTC, Ivan-Nebogatikov commented on Semestr3/Homework2/Homework2/Computer.cs
> +        public Computer(OS os, bool infection, List<int> neigh)
Это правда

2016-11-29 13:00 UTC, Ivan-Nebogatikov commented on Semestr3/Homework2/Homework2Tests/NetworkTests.cs
> +            network.StartNetwork();
Да, все компьютеры заражены => делаем проверку, что все заражены, и выходим, т.к. состояние стабильное

2016-11-29 20:16 UTC, yurii-litvinov requested changes

2016-11-29 20:16 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2/Computer.cs
> +        public Computer(OS os, bool infection, List<int> heighbours)
Они же "neighbors"

2016-11-29 20:16 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2Tests/NetworkTests.cs
> +            network.StartNetwork();
Так не пойдёт :) Надо проверять, что распространение вируса по сети удовлетворяет условию задачи --- например, что на одном ходу могут заразиться только компьютеры, соседние с заражённым, так что в сети (*) -- ( ) -- ( ), где (*) означает заражённый компьютер, а ( ) --- незаражённый, заражение занимает минимум два хода. В Вашем решении, кстати, такой тест может пройти, но это будет случайность :)

2016-11-29 20:30 UTC, Ivan-Nebogatikov commented on Semestr3/Homework2/Homework2Tests/NetworkTests.cs
> +            network.StartNetwork();
То есть надо сделать заражение и проверку public методами, и вызывать их из теста?

2016-11-29 20:35 UTC, yurii-litvinov commented on Semestr3/Homework2/Homework2Tests/NetworkTests.cs
> +            network.StartNetwork();
Можно, но это повредит инкапсуляции. Можно разделить Network на два класса, один будет отвечать за заражение на одном ходу, второй --- за выполнение ходов, пока сеть не стабилизируется.

2016-12-16 05:56 UTC, yurii-litvinov approved these changes

2016-12-16 05:56 UTC, merged