Homework 8
Ivan-Nebogatikov/Homeworks pull request #38
Opened 2017-04-25 18:45 UTC by Ivan-Nebogatikov

2017-05-08 19:41 UTC, yurii-litvinov requested changes

2017-05-08 19:41 UTC, yurii-litvinov commented on NextHomework/Homework8/Task1/Program.fs
> +            let html = reader.ReadToEnd()
Нет ли тут копипаста с getPage? Можно было сделать это async-ом, а в getPage синхронно его вызывать.

2017-05-08 19:41 UTC, yurii-litvinov commented on NextHomework/Homework8/Task1/Program.fs
> +    let matchesSeq : seq<Match> = Seq.cast <| regex.Matches(page)
У меня виснет намертво при попытке пройти по коллекции матчей, как кажется, из-за http://www.regular-expressions.info/catastrophic.html. По крайней мере, замена `.` на `[.]` решает проблему.

2017-05-09 08:28 UTC, Ivan-Nebogatikov commented on NextHomework/Homework8/Task1/Program.fs
> +    let matchesSeq : seq<Match> = Seq.cast <| regex.Matches(page)
При такой замене теряется половина сайтов с codforces-a

2017-05-09 09:53 UTC, yurii-litvinov approved these changes
Да, вот теперь всё работает

2017-05-16 14:38 UTC, merged